# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Text on the contact page')),
                ('address', models.CharField(max_length=255, verbose_name='Address')),
                ('email', models.CharField(max_length=255, verbose_name='Email')),
                ('phone', models.CharField(max_length=255, verbose_name='Phone')),
                ('facebook', models.CharField(blank=True, max_length=255, null=True, verbose_name='Facebook page link')),
                ('instagram', models.CharField(blank=True, max_length=255, null=True, verbose_name='Instagram page link')),
                ('behance', models.CharField(blank=True, max_length=255, null=True, verbose_name='Behance page link')),
                ('all_rights_reserved', models.CharField(blank=True, max_length=255, null=True, verbose_name='All rights text, can change')),
            ],
            options={
                'verbose_name': 'Contact',
                'verbose_name_plural': 'Contacts',
            },
        ),
    ]
