# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-19 11:58
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of category')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Title of portfolio')),
                ('main_image', models.ImageField(upload_to='images/main_images', verbose_name='Main image for portfolio')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='global description of work')),
                ('category', models.ManyToManyField(to='portfolio.Category', verbose_name='Choose one or more than one category of work')),
            ],
            options={
                'verbose_name': 'porfolio',
                'verbose_name_plural': 'portfolio',
            },
        ),
        migrations.CreateModel(
            name='PortfolioElements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/elements', verbose_name='Choose image')),
                ('image_title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Image title')),
                ('text', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Description text')),
                ('portfolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='portfolio.Portfolio', verbose_name='Portfolio')),
            ],
            options={
                'verbose_name': 'Element',
                'verbose_name_plural': 'Elements',
            },
        ),
    ]
