# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-07-20 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='image_bg',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Background of main image'),
        ),
    ]
